### ISSUE TITLE
please show an example of how to provide multiple kmers

### ISSUE THREAD

**Issue by rjsorr** [HudsonAlpha/fmlrc2#28]
following the default example does not work. I want to run 21, 59, 79 and 127, but writing "-k 21 59 79 127" as the default indicates does not work neither does [21, 59] method nor k=[21, 59, 79] method, as written both in the readme. So how to invoke a k 21, 59, 79 and 127? please write the answer without pointing to the default

**Comment by holtjma** [comment]
The first method you posted is the correct one.  Note that you may need a “--“ after the list to indicate the end of the list if you put the required fields directly after.  I will look into adding a clear example to the README.

**Comment by rjsorr** [comment]
cheers for the quick answer! can confirm that "-k 21 59 79 127 --" works.
regards

**Comment by holtjma** [comment]
Re-opening just so I remember to add docs later

**Comment by holtjma** [comment]
The README has a short FAQ now with this specific question:
[https://github.com/HudsonAlpha/fmlrc2#how-do-i-set-multiple-custom-k-mer-sizes](https://github.com/HudsonAlpha/fmlrc2#how-do-i-set-multiple-custom-k-mer-sizes)
